---
  - name: Ping my hosts
    ansible.builtin.ping:
  
  - name: Install package acl
    apt:
      name: acl
      state: present
      update_cache: yes

  - name: Install required Python packages
    apt:
      name: python3-psycopg2
      state: present
      update_cache: yes

